---

stages:
  - lint
  - build


include:

  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'

  - project: 'saltbox/ci-lib'
    file: 'mirror-repo.yml'

  - project: 'saltbox/ci-lib'
    file: 'close-github-pr.yml'


.lint-job:
  stage: lint
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    APK_CACHE_DIR: '$CI_PROJECT_DIR/.cache/apk'
    ADAPTER_ENV_FILE: 'tests/test.env'
  image: python:3.12-alpine
  before_script:
    - mkdir --parents "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" cargo git
    - pip3 install -r local_requirements.txt
    - pip3 install -e .[dev]
    - python -V
  cache:
    paths:
      - '$PIP_CACHE_DIR'
      - '$APK_CACHE_DIR'


Ruff:
  extends: .lint-job
  script: 'ruff check .'


Mypy:
  extends: .lint-job
  script: 'mypy .'


Build FileBrowser Adapter image:
  stage: build
  extends: .build-image
  variables:
    TARGET: main


Mirror Repository:
  extends: .mirror-repo
  stage: build


Check for GitHub PR to close:
  extends: .close-github-pr
  stage: build
